---
- hosts: servers
  tasks:
    - name: create vhost directory
      file:
        path=/etc/nginx/vhost
        state=directory
        owner=root
        group=root
        mode=0755
    - name: create myfirstpage document root
      file:
        path=/usr/share/nginx/www/myfirstpage
        state=directory
        owner=root
        group=root
        mode=0755
    - name: upload 1.html
      copy: src=html/1.html dest=/usr/share/nginx/www/myfirstpage/ mode=0644
    - name: create mysecondpage document root
      file:
        path=/usr/share/nginx/www/mysecondpage
        state=directory
        owner=root
        group=root
        mode=0755
    - name: upload 2.html
      copy: src=html/2.html dest=/usr/share/nginx/www/mysecondpage/ mode=0644
    - name: create mythirdpage document root
      file:
        path=/usr/share/nginx/www/mythirdpage
        state=directory
        owner=root
        group=root
        mode=0755
    - name: upload 3.html
      copy: src=html/3.html dest=/usr/share/nginx/www/mythirdpage/ mode=0644
    - name: Create a myfirstpage.com file
      template:
        src=vhost/myfirstpage.com.conf
        dest=/etc/nginx/vhost/myfirstpage.com.conf
        owner=root
        group=root
        mode=0644
    - name: Create mysecondpage.com file
      template:
        src=vhost/mysecondpage.com.conf
        dest=/etc/nginx/vhost/mysecondpage.com.conf
        owner=root
        group=root
        mode=0644
    - name: Create mythirdpage.com file
      template:
        src=vhost/mythirdpage.com.conf
        dest=/etc/nginx/vhost/mythirdpage.com.conf
        owner=root
        group=root
        mode=0644

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
